config/routes.rb
Rails.application.routes.draw do
  root to: "site#index"

  ActiveAdmin.routes(self)

  devise_for :users

  resources :posts do
    resources :comments
    post "like", to: "posts#like"
    post "unlike", to: "posts#unlike"
  end

  resources :users, only: [:index, :show]

  # Site
  get "download", to: "site#download"
  get 'online_view', to: 'site#online_view'

  # Accounts
  get "account/user_info", to: "accounts#user_info"
  patch "account/update_user_info", to: "accounts#update_user_info"
  get "account/notifications", to: "accounts#notifications"
  get "account/my_posts", to: "accounts#my_posts"

  # Notifications
  get "account/notifications/:id/read", to: "notifications#read", as: "account_notification_read"
  get "account/notifications/read", to: "notifications#read_all"

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def user_info
    @user = current_user
  end

  def update_user_info
    @user = current_user

    @user.first_name = user_params[:first_name]
    @user.last_name = user_params[:last_name]
    @user.date_of_birth = DateTime.parse(user_params[:date_of_birth])
    @user.gender = user_params[:gender]
    @user.bio = user_params[:bio]

    if user_params[:avatar].present?
      @user.avatar.attach(user_params[:avatar])
    end

    if @user.save
      redirect_to account_user_info_path, notice: "Ваши  данные успешно обновлены."
    else
      flash[:alert] = "При обновлении данных возникли ошибки."
      render :user_info
    end
  end

  def notifications
    @notifications = Notification.where(user: current_user).page params[:page]
  end

  def my_posts
    @posts = Post.where(user: current_user).page params[:page]
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :date_of_birth, :gender, :bio, :avatar)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/shared/_left_menu.html.haml
.nav.flex-column.nav-pills{ "aria-orientation": "vertical" }
  = link_to "Личная информация", account_user_info_path, class: "nav-link #{'active' if current_page?(account_user_info_path)}"
  = link_to account_notifications_path, class: "nav-link #{'active' if current_page?(account_notifications_path)}" do
    Уведомления
    %span.badge.notify-count-menu-icon= current_user.notifications.unread.count if current_user.notifications.unread.count > 0
  = link_to "Мои посты", account_my_posts_path, class: "nav-link #{'active' if current_page?(account_my_posts_path)}"
  = link_to "Панель администратора", admin_root_path, class: "nav-link" if current_user.admin?

app/views/accounts/shared/_notification.html.haml
- if notification.subject.present?
  .notify-container
    .notify-header
      .notify-date
        = notification.created_at.strftime("%d.%m.%Y %H:%M")
      .notify-read.ml-auto
        - if notification.read?
          .blue= "Прочитано"
        - else
          .red= "Не прочитано"
    .notify-content
      = notification.content
      - if notification.subject_type == "Comment"
        .notify-comment-text
          Текст комментария:
          = notification.subject.body
    .notify-links
      - unless notification.read?
        = link_to "Отметить прочитанным", account_notification_read_path(notification)
      - if notification.subject_type == "Comment"
        = link_to "Перейти к посту", notification.subject.post
      - if notification.subject_type == "Post"
        = link_to "Перейти к посту", notification.subject
- else
  - notification.destroy