config/routes.rb
Rails.application.routes.draw do
  root to: "site#index"

  ActiveAdmin.routes(self)

  devise_for :users

  resources :posts do
    resources :comments
    post "like", to: "posts#like"
    post "unlike", to: "posts#unlike"
  end

  resources :users, only: [:index, :show]

  # Site
  get "download", to: "site#download"
  get 'online_view', to: 'site#online_view'

  # Accounts
  get "account/user_info", to: "accounts#user_info"
  patch "account/update_user_info", to: "accounts#update_user_info"
  get "account/notifications", to: "accounts#notifications"
  get "account/my_posts", to: "accounts#my_posts"

  # Notifications
  get "account/notifications/:id/read", to: "notifications#read", as: "account_notification_read"
  get "account/notifications/read", to: "notifications#read_all"

end

app/views/shared/_about_program_frame.html.haml
.row
  .col-sm-6
    = image_tag path_to_image('program_window_1.png'), class: 'about-program-img'
  .col-sm-6
    .about-program-content
      .title
        Fractal View
      .content
        Данное приложение позволяет создавать изображения некторых типов фракталов, таких как Множество Мандельброта, множество Жюлиа, лямбда - фрактал.
      .content
        Также есть возможность выбора размера изображения, качества прорисовки и цветовую схему.
      .link-title
        Перейти на страницу загрузки
      = link_to download_path do
        .link-icon
          %i.fas.fa-cloud-download-alt

app/views/shared/_footer.html.haml
%footer.footer
  .container
    .row
      .col-sm-6
        .mt-5
          %ul.footer-nav-links
            %li.nav-item.nav-item-link
              = link_to "Онлайн", online_view_path, class: "#{'nav-active' if current_page?(online_view_path)}"
            %li.nav-item-link
              = link_to "Загрузить", download_path, class: "#{'nav-active' if current_page?(download_path)}"
      .col-sm-6
        %ul.footer-social-links.mt-100
          - SocialMedia.all.each do |item|
            %li.nav-item-link
              = link_to item.site_url do
                = content_tag('i', nil, class: item.icon_class)

app/views/shared/_header.html.haml
%header
  .container
    .p-4
    %nav.navbar.navbar-expand-sm
      = link_to :root do
        .navbar-brand.text-30.text-w-600.text-white
          Fractal View
      %ul.navbar-nav.ml-auto
        %li.nav-item.nav-item-link
          = link_to "Онлайн", online_view_path, class: "#{'nav-active' if current_page?(online_view_path)}"
        %li.nav-item.nav-item-link
          = link_to "Загрузить", download_path, class: "#{'nav-active' if current_page?(download_path)}"

        %li.nav-item.nav-item-link.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle.p-0{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Пользователи
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            = link_to "Работы пользователей", posts_path, class: "dropdown-item #{'nav-active' if current_page?(posts_path)}"
            = link_to "Список пользователей", users_path, class: "dropdown-item #{'nav-active' if current_page?(users_path)}"

        -  if current_user.present?
          %li.nav-item.nav-item-link
            = link_to "Кабинет", account_user_info_path, class: "#{'nav-active' if current_controller?('accounts')}"
          %li.nav-item.nav-item-link
            = link_to(destroy_user_session_path, method: :delete) do
              = content_tag('i', nil, class: 'fas fa-sign-out-alt text-white text-20')
        - else
          %li.nav-item.nav-item-link
            = link_to "", new_user_session_path, class: "fas fa-sign-in-alt"

app/views/shared/_posts_carousel.html.haml
.row
  .col-sm-12
    .text-30.text-white.text-center.mb-5
      Последние добавленные пользователями изображения
    #post-carousel.carousel.slide{"data-ride" => "carousel"}
      .carousel-inner
        - @posts.each_with_index do |post, index|
          - if index == 0
            .carousel-item.active{"data-interval" => "5000"}
              = link_to post do
                = image_tag(url_for(post.main_picture), class: "d-block carousel-img-size")
          - else
            .carousel-item{"data-interval" => "5000"}
              = link_to post do
                = image_tag(url_for(post.main_picture), class: "d-block carousel-img-size")
      %a.carousel-control-prev{"data-slide" => "prev", :href => "#post-carousel", :role => "button"}
        %span.carousel-control-prev-icon{"aria-hidden" => "true"}
      %a.carousel-control-next{"data-slide" => "next", :href => "#post-carousel", :role => "button"}
        %span.carousel-control-next-icon{"aria-hidden" => "true"}