config/routes.rb
Rails.application.routes.draw do
  root to: "site#index"

  ActiveAdmin.routes(self)

  devise_for :users

  resources :posts do
    resources :comments
    post "like", to: "posts#like"
    post "unlike", to: "posts#unlike"
  end

  resources :users, only: [:index, :show]

  # Site
  get "download", to: "site#download"
  get 'online_view', to: 'site#online_view'

  # Accounts
  get "account/user_info", to: "accounts#user_info"
  patch "account/update_user_info", to: "accounts#update_user_info"
  get "account/notifications", to: "accounts#notifications"
  get "account/my_posts", to: "accounts#my_posts"

  # Notifications
  get "account/notifications/:id/read", to: "notifications#read", as: "account_notification_read"
  get "account/notifications/read", to: "notifications#read_all"

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :notifications, as: :subject
  has_many :likes

  has_one_attached :main_picture

  validates :title, :description, :main_picture, presence: true

  paginates_per 2

  after_create :notify_users

  def liked_by_user?(user)
    Like.exists?(user: user, post: self)
  end

  def like!(user)
    unless liked_by_user?(user)
      Like.create!(user: user, post: self)
    end
  end

  def unlike!(user)
    if liked_by_user?(user)
      Like.find_by(user: user, post: self).destroy
    end
  end

  def likes_count
    Like.where(post: self).count
  end

  private

  def notify_users
    users = User.where.not(id: self.user.id)
    Notification.notify_for_post_created(users: users, subject: self)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_post, only: [ :like, :unlike ]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all.page(params[:page])
  end

  def create
    @post = Post.new(post_params.merge(user: current_user))
    @post.main_picture.attach(params[:post][:main_picture])

    if @post.save
      redirect_to @post, notice: "Пост успешно создан."
    else
      flash[:alert] = "При создании поста возникли ошибки"
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  def like
    @post.like!(current_user)
    redirect_to @post
  end

  def unlike
    @post.unlike!(current_user)
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def post_params
    params.require(:post).permit(:title, :description)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.haml
.row
  .col-sm-8
    = render partial: "posts/shared/post", collection: @posts
    .d-flex.justify-content-center
      = paginate @posts, theme: 'twitter-bootstrap-4'

  .col-sm-4
    .p-5
    = search_form_for @q do |f|
      .form-group
        = f.label :title, class: "form-label text-white"
        = f.search_field :title_cont, class: "form-control"
      .form-group
        = f.label :description, class: "form-label text-white"
        = f.search_field :description_cont, class: "form-control"
      .form-group
        = f.submit "Искать", class: "btn btn-success btn-lg btn-block"

    = link_to "Новый пост", new_post_path, class: 'btn btn-primary btn-lg btn-block'

app/views/posts/new.html.haml
.py-100

.row
  .col-sm-6.offset-3
    %h2.mb-5.text-white Создание поста
    .row
      .col-sm-12
        .text-white.p-2.mb-2
          = @post.errors.full_messages if @post.errors.full_messages.present?
    .row
      .col-sm-12
        = form_with(model: @post, local: true) do |f|
          .form-group
            = f.label :title, class: "form-label text-white"
            = f.text_field :title, class: "form-control"
          .form-group
            = f.label :description, class: "form-label text-white"
            = f.text_area :description, class: "form-control"
          .form-group
            = f.file_field :main_picture
          .form-group
            = f.submit "Создать", class: "btn btn-success btn-lg btn-block"

app/views/posts/show.html.haml
.row
  .col-sm-8
    .post-container
      .post-title
        = @post.title

      .post-img
        = image_tag(url_for(@post.main_picture))

      .d-flex.mb-3
        .post-like
          - if @post.liked_by_user?(current_user)
            = link_to post_unlike_path(@post), method: :post, local: true do
              %i.fas.fa-heart
              = @post.likes_count
          - else
            = link_to post_like_path(@post), method: :post, local: true do
              %i.far.fa-heart
              = @post.likes_count

        .post-img-link.ml-auto
          = link_to rails_blob_path(@post.main_picture, disposition: "attachment") do
            %i.fas.fa-download

      .post-description
        = @post.description

      .post-footer
        .post-user
          = "Отправил: "
          = link_to(@post.user.full_name, user_path(@post.user))
        .post-date
          = "Дата: #{@post.created_at.strftime("%d.%m.%Y %H:%M")}"

  .col-sm-4
    .p-5

    - if current_user.present?
      = form_with(url: post_comments_path(@post), method: :post, local: true, class: "mb-5") do |f|
        .form-group
          = f.label "Текст комментария:", class: "form-label text-white"
          = f.text_area :text, class: "form-control form-control-lg", onkeyup: "checkField()", placeholder: "Мин. 2 символа"
        = f.submit "Добавить комментарий", class: "btn btn-primary btn-block text-white", id: "comment_submit"

    - if @comments.present?
      %p.text-white.p-2.mb-2 Комментарии пользователей:

    = render partial: "posts/shared/comment", collection: @comments

    .d-flex.justify-content-center.mt-5
      = paginate @comments, theme: 'twitter-bootstrap-4'
      
:javascript
  $(function() {
    $('#comment_submit').attr('disabled', 'disabled');
  });

  function checkField() {
    if ($('#text').val().length >= 2) {
        $('#comment_submit').removeAttr('disabled');
    } else {
        $('#comment_submit').attr('disabled', 'disabled');
    }
  }