config/routes.rb
Rails.application.routes.draw do
  root to: "site#index"

  ActiveAdmin.routes(self)

  devise_for :users

  resources :posts do
    resources :comments
    post "like", to: "posts#like"
    post "unlike", to: "posts#unlike"
  end

  resources :users, only: [:index, :show]

  # Site
  get "download", to: "site#download"
  get 'online_view', to: 'site#online_view'

  # Accounts
  get "account/user_info", to: "accounts#user_info"
  patch "account/update_user_info", to: "accounts#update_user_info"
  get "account/notifications", to: "accounts#notifications"
  get "account/my_posts", to: "accounts#my_posts"

  # Notifications
  get "account/notifications/:id/read", to: "notifications#read", as: "account_notification_read"
  get "account/notifications/read", to: "notifications#read_all"

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def user_info
    @user = current_user
  end

  def update_user_info
    @user = current_user

    @user.first_name = user_params[:first_name]
    @user.last_name = user_params[:last_name]
    @user.date_of_birth = DateTime.parse(user_params[:date_of_birth])
    @user.gender = user_params[:gender]
    @user.bio = user_params[:bio]

    if user_params[:avatar].present?
      @user.avatar.attach(user_params[:avatar])
    end

    if @user.save
      redirect_to account_user_info_path, notice: "Ваши  данные успешно обновлены."
    else
      flash[:alert] = "При обновлении данных возникли ошибки."
      render :user_info
    end
  end

  def notifications
    @notifications = Notification.where(user: current_user).page params[:page]
  end

  def my_posts
    @posts = Post.where(user: current_user).page params[:page]
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :date_of_birth, :gender, :bio, :avatar)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/my_posts.html.haml
.row
  .col-sm-4
    .py-100
    = render partial: "accounts/shared/left_menu"

  .col-sm-8
    = render partial: "posts/shared/post", collection: @posts
    .d-flex.justify-content-center
      = paginate @posts, theme: 'twitter-bootstrap-4'

app/views/accounts/notifications.html.haml
.row
  .col-sm-4
    .py-100
    = render partial: "accounts/shared/left_menu"

  .col-sm-8
    .p-5
    - if current_user.notifications.count > 0
      .d-flex.mb-4
        = link_to "Отметить все прочитанным", account_notifications_read_path, class: "btn btn-primary ml-auto"

      = render partial: "accounts/shared/notification", collection: @notifications
      .d-flex.justify-content-center
        = paginate @notifications, theme: 'twitter-bootstrap-4'
    - else
      .text-white.text-20.text-w-600.text-center
        У вас нет уведомлений

app/views/accounts/user_info.html.haml
.row
  .col-sm-4
    .py-100
    = render partial: "accounts/shared/left_menu"
  .col-sm-8
    .p-5
    %h2.mb-5.text-white Редактирование личной информации
    .row
      .col-sm-12
        .text-white.p-2.mb-2
          = @user.errors.full_messages if @user.errors.full_messages.present?
    .row
      .col-sm-12
        = form_with model: @user, url: account_update_user_info_path, local: true do |f|
          .form-group
            = f.label :first_name, class: "form-label text-white"
            = f.text_field :first_name, class: "form-control"
          .form-group
            = f.label :last_name, class: "form-label text-white"
            = f.text_field :last_name, class: "form-control"
          .form-group
            = f.label :date_of_birth, class: "form-label text-white"
            = f.date_field :date_of_birth, class: "form-control"
          .form-group
            = f.label :gender, class: "form-label text-white"
            = f.select(:gender, [["Мужской", "male"], ["Женский", "female"]], {}, class: "form-control")
          .form-group
            = f.label :bio, class: "form-label text-white"
            = f.text_area :bio, class: "form-control"
          .form-group
            = f.file_field :avatar
          .form-group
            = f.submit "Сохранить", class: "btn btn-success btn-lg btn-block"